adjective1 = input("enetr adjective{description}")
noun1 = input("enetr noun{description}")
djective2 = input("enetr adjective{person, palce or someething}")
verb1 = input("enetr verb ending with 'ing'")
djective13 = input("enetr adjective{description}")
prin(f"Today i want to  {adjective1} zoo.")
print(f"In the exbition , I saw somthing a {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was{adjective3}!")